# ************************************************************************* #
# This file is part of Shard.                                               #
#                                                                           #
# Shard is free software: you can redistribute it and/or modify             #
# it under the terms of the GNU Affero General Public License as            #
# published by the Free Software Foundation.                                #
#                                                                           #
# This program is distributed in the hope that it will be useful,           #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the              #
# GNU Affero General Public License for more details.                       #
#                                                                           #
# You should have received a copy of the GNU Affero General Public License  #
# along with this program. If not, see <http://www.gnu.org/licenses/>.      #
# ************************************************************************* #

language: generic
sudo: required
dist: trusty
group: edge

services:
    - docker

branches:
    except:
        - tokenizer-devel
        - parser-devel

matrix:
    include:
        - compiler: gcc
          env:
            - CC=gcc-7
            - CXX=g++-7
            - PKG=g++-7

install:
    - docker build -t shard --build-arg PKG=$PKG --build-arg CC=$CC --build-arg CXX=$CXX .
    - mkdir -p ${TRAVIS_BUILD_DIR}/build
    - docker run -v ${TRAVIS_BUILD_DIR}:/opt/shard -v ${TRAVIS_BUILD_DIR}/build:/opt/build shard cmake -DCMAKE_BUILD_TYPE=release -DSHARD_BUILD_TESTS=On "/opt/shard"

script:
    - docker run -v ${TRAVIS_BUILD_DIR}:/opt/shard -v ${TRAVIS_BUILD_DIR}/build:/opt/build shard cmake --build .
    - docker run -v ${TRAVIS_BUILD_DIR}:/opt/shard -v ${TRAVIS_BUILD_DIR}/build:/opt/build shard ctest --verbose

# ######################################################################### #
