# ************************************************************************* #
# This file is part of Shard.                                               #
#                                                                           #
# Shard is free software: you can redistribute it and/or modify             #
# it under the terms of the GNU Affero General Public License as            #
# published by the Free Software Foundation.                                #
#                                                                           #
# This program is distributed in the hope that it will be useful,           #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the              #
# GNU Affero General Public License for more details.                       #
#                                                                           #
# You should have received a copy of the GNU Affero General Public License  #
# along with this program. If not, see <http://www.gnu.org/licenses/>.      #
# ************************************************************************* #

language: generic
sudo: required
services:
    - docker

matrix:
    include:
        - compiler: gcc
          env:
            - CC=gcc-5
            - CXX=g++-5
            - PKG=g++-5
        - compiler: clang
          env:
            - CC=clang-3.6
            - CXX=clang++-3.6
            - PKG=clang-3.6
        - compiler: clang
          env:
            - CC=clang-3.7
            - CXX=clang++-3.7
            - PKG=clang-3.7
        - compiler: clang
          env:
            - CC=clang-3.8
            - CXX=clang++-3.8
            - PKG=clang-3.8

install:
    - docker build -t shard --build-arg PKG=$PKG --build-arg CC=$CC --build-arg CXX=$CXX .
    - mkdir -p ${TRAVIS_BUILD_DIR}/build
    - docker run -v ${TRAVIS_BUILD_DIR}:/opt/build shard cmake -DCMAKE_BUILD_TYPE=release -DSHARD_BUILD_TESTS=On ..

script:
    - docker run -v ${TRAVIS_BUILD_DIR}:/opt/build shard cmake --build .
    - docker run -v ${TRAVIS_BUILD_DIR}:/opt/build shard ctest --verbose

# ######################################################################### #